  name: Fix Release

  on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Номер релиза'
          required: true

  env:
    APP_NAME: app
    REGISTRY_HOST: cr.yandex
    REESTR_ID: crpvn4spj16vplr31itj

  jobs:
    lint-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout release branch
          uses: actions/checkout@v4
          with:
            ref: releases/${{ github.event.inputs.version }}

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install dependencies
          run: npm ci

        - name: Lint code
          run: npm run lint

        - name: Run tests
          run: npm test

    build-and-push-fix:
      needs: lint-test
      runs-on: ubuntu-latest
      env:
        VERSION: ${{ github.event.inputs.version }}
        CR_PATH: ${{ env.REGISTRY_HOST }}/${{ env.REESTR_ID }}
      steps:
        - name: Build Fix Docker image
          run: |
            FIX_NUM=${{ github.run_number }}
            docker build \
              -t "$CR_PATH/$APP_NAME:${VERSION}_fix${FIX_NUM}" \
              -t "$CR_PATH/$APP_NAME:latest" .

        - name: Authenticate to Yandex Container Registry
          run: |
            printf '%s' "${{ secrets.YCR_TOKEN }}" \
              | docker login --username oauth --password-stdin "${{ env.REGISTRY_HOST }}"

        - name: Push Fix images
          run: |
            FIX_NUM=${{ github.run_number }}
            docker push "$CR_PATH/$APP_NAME:${VERSION}_fix${FIX_NUM}"
            docker push "$CR_PATH/$APP_NAME:latest"

    tag-and-comment:
      needs: build-and-push-fix
      runs-on: ubuntu-latest
      env:
        VERSION: ${{ github.event.inputs.version }}
        CR_PATH: ${{ env.REGISTRY_HOST }}/${{ env.REESTR_ID }}
      steps:
        - name: Checkout release branch
          uses: actions/checkout@v4
          with:
            ref: releases/${{ env.VERSION }}

        - name: Create fix release tag
          run: |
            FIX_NUM=${{ github.run_number }}
            TAG="${VERSION}_fix${FIX_NUM}"
            git config user.name  "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git tag -a "$TAG" -m "Fix release $TAG"
            git push origin "$TAG"

        - name: Comment on release issue
          run: |
            FIX_NUM=${{ github.run_number }}
            TAG="${VERSION}_fix${FIX_NUM}"
            LOG=$(git log ${VERSION}_fix$((FIX_NUM-1))..HEAD --pretty=format:'- %s (%an)' || echo '- no additional commits')
            gh issue comment "${VERSION}" \
              --body "Fix $TAG deployed on $(date +'%Y-%m-%d') by @${{ github.actor }}\n\nCommits:\n${LOG}\n\nDocker images:\n- $CR_PATH/$APP_NAME:$TAG\n- $CR_PATH/$APP_NAME:latest"
